### ISSUE TITLE
Capacitor Support

### ISSUE THREAD

**Issue by sandstrom** [pushy-me/pushy-cordova#19]
Do you have plans to support Capacitor in Pushy? 

It's a spiritual successor to Cordova, built by Ionic. With some adjustments this SDK should be fairly easy to adapt so that it'll work with Capacitor.

More details here:
https://capacitor.ionicframework.com/docs/plugins

**Comment by pushy-me** [comment]
Hi @sandstrom,
Thanks for your inquiry!

At the moment there isn't enough demand for a Capacitor plugin -- however, if you would like to attempt to work on this you are more than welcome!

We'll definitely let you know if this changes and we begin working on an official plugin.

**Comment by sandstrom** [comment]
Thanks for the update! 

In case it helps, I think many Cordova plugins should work in Capacitor out-of-the-box. So what you could do is simply test if that's the case (likely), and update the readme to reflect that.

You could then use some telemetry (that I presume you already have) to gauge usage of Capacitor.

**Comment by pushy-me** [comment]
Hi @sandstrom,
Indeed Capacitor seems to work well out of the box for our Cordova plugin!

You can add it to your Capacitor project as follows:

```
npm install add pushy-cordova
npm install ./node_modules/pushy-cordova/receiver/

npx cap sync
```

In addition, edit `capacitor-welcome.js` or any other main element in your Capacitor project, and add the following lines under `connectedCallback()`:

```
    // Start the Pushy service
    Pushy.listen();

    // Request the WRITE_EXTERNAL_STORAGE permission so that the Pushy SDK will be able to persist the device token in the external storage
    Pushy.requestStoragePermission();

    // Register the device for push notifications
    Pushy.register(function (err, deviceToken) {
      // Handle registration errors
      if (err) {
        return alert(err);
      }

      // Display an alert with device token
      alert('Pushy device token: ' + deviceToken);

      // Send the token to your backend server via an HTTP GET request
      //await fetch('https://your.api.hostname/register/device?token=' + deviceToken);

      // Succeeded, optionally do something to alert the user
    });


    // Listen for push notifications
    Pushy.setNotificationListener(function (data) {
      // Print notification payload data
      console.log('Received notification: ' + JSON.stringify(data));

      // Display an alert with the "message" payload value
      alert(data.message);
    });
```

Run your app on Android to test:

```
npx cap open android
```

We have yet to test iOS but I have a feeling it will work as well. You will need to perform some other steps listed in our [Ionic guide](https://pushy.me/docs/additional-platforms/ionic) though.

When we finish testing on iOS and writing a guide for Capacitor we'll publish it and let you know.

**Comment by sandstrom** [comment]
@pushy-me Awesome, happy to hear!

Great that you are writing a guide for Capacitor, I think that will help you bring in more customers! 😄

**Comment by pushy** [comment]
@sandstrom Our official Capacitor docs are here 😄 
https://pushy.me/docs/additional-platforms/capacitor

**Comment by jbwl** [comment]
> In addition, edit `capacitor-welcome.js` or any other main element in your Capacitor project

I'm stuck here (and the Pushy official Capacitor docs do not have additional information). I am trying to make Pushy work with a Capacitor project inside a quasar/vue app. I added an ios project, which was created OK and runs fine.

But: I do not understand where exactly I am supposed to add the needed Pushy code for initialization. Inside the Capacitor project, I have a www directory which only contains an index.html file (which must not be edited). 

Even though inside node_modules under the capacitor project, I do have a capacitor-welcome.js file, I don't think it is right to add the code there as it would be overwritten when the node module is updated...

Also, I am not sure what is meant by "or any other main element in your Capacitor project" - my Capacitor project does not contain "elements", just configuration files and a Xcode Project folder which also does not have .js files.

I assume that Capacitor was changed between Nov 21, 2019 and now, and its project structure has changed significantly, so it would be good if the docs could be updated.

Please let me know at what level I am supposed to add the Pushy code. As stated above, the project structure I have is: Vue/Quasar-App -> Capacitor Project -> XCode Project

Thank you!

**Comment by pushy** [comment]
Hi @jbwl,
For a Quasar Capacitor app, simply add the Pushy code in one of your Quasar project’s `pages/layouts/components` Vue files.

**Comment by jbwl** [comment]
> For a Quasar Capacitor app, simply add the Pushy code in one of your Quasar project’s `pages/layouts/components` Vue files.

Thank you for your help. I did try that before asking the question above. But I'm missing some pieces of the puzzle which is also caused by lack of knowledge on my part. But simply following the Pushy docs for Capacitor does not seem to include the necessary dependencies to enable me to reference Pushy in my app:

As per the instructions at https://pushy.me/docs/additional-platforms/capacitor:

inside my Quasar project (top level), I did:
```
npm install pushy-cordova
npm install ./node_modules/pushy-cordova/receiver/
```
after that, my Quasar project's package.json contains: 
```
"pushy-cordova": "^1.0.30",
"pushy-cordova-receiver": "file:node_modules/pushy-cordova/receiver",
```

now, when I
```
npx cap sync
```

this results in the error message:
```
[error] Capacitor could not find the web assets directory "/Volumes/Secondary/Users/c/projects/quasarapp/www".
```

Writing a boot file to init Pushy in my app [(as per the Quasar conventions)](https://quasar.dev/quasar-cli/cli-documentation/boot-files#When-to-use-boot-files), importing Pushy's libraries is not straightforward (or maybe I need exact instructions how to do it) - when I try to write a boot file like this:

```
import { Platform } from "quasar";
import Pushy from "pushy-cordova";

export default async () => {
  if (Platform.is.capacitor) {
    console.log("Running on capacitor");
    Pushy.listen();
  }
};
```

the app does not compile:

```
This dependency was not found:

* pushy-cordova in ./src/boot/pushy.js

To install it, you can run: npm install --save pushy-cordova
```

As of now just following the docs doesn't seem to be enough to include Pushy in my app.

More help would be highly appreciated :-)

**Comment by pushy** [comment]
Hi @jbwl,
The issue may arise due to your explicit import of `pushy-cordova`. There is actually no need to manually import our library, as it becomes a global variable in the JS environment when you install our Cordova plugin.

Therefore, remove the line:
```
import Pushy from "pushy-cordova";
```

And for debugging, try using `console.log` to see if `Pushy` is indeed a global:
```
console.log(Pushy);
```

**Comment by jbwl** [comment]
Hi again, thank you for your ongoing support. Unfortunately, in the context of a Quasar app, I still can't manage to setup and init Pushy. Quasar of course uses its own app structure - for instance boot files to setup and init libraries. But as you said, Pushy should be global without any imports.

I made a barebones Quasar sandbox app here, with the required npm packages for Pushy:

[https://codesandbox.io/s/pushy-in-quasar-app-vcecy
](https://codesandbox.io/s/pushy-in-quasar-app-vcecy
)

Pushy is undefined. Would you be able to get that example to work? All I need is Pushy to init correctly and I think I can figure out the rest. Thank you so much!

**Comment by pushy** [comment]
Hi @jbwl,
It seems that for a Quasar app to consume and have access to a Cordova plugin (the Pushy plugin), based on [the docs](https://quasar.dev/quasar-cli/developing-cordova-apps/cordova-plugins#Caveat), you need to do two things:

1) When you install our plugin, you need to `cd` into the `src-cordova` folder in your Quasar project, and only then install our plugin:
```
cordova plugin add pushy-cordova
cordova plugin add ./plugins/pushy-cordova/receiver/
```

2) Next, in one of your Quasar project’s `pages/layouts/components` Vue files, add the following to listen for the `deviceready` event, and only then try to access the Pushy plugin via `window.Pushy`:

```
<script>
// Listen to the 'deviceready' event:
document.addEventListener('deviceready', () => {
  // Try to access Pushy
 console.log(window.Pushy);
}, false)

export default {
  // we are sure 'deviceready' has been triggered here
}
</script>
```

Good luck.

**Comment by jbwl** [comment]
Thanks again, but I'm not using Cordova, but Capacitor. And Capacitor does not work like Cordova in this regard (plugins). 

So I am wondering how your Capacitor docs can be applied: https://pushy.me/docs/additional-platforms/capacitor 

Are they outdated?

**Comment by jbwl** [comment]
Hi @pushy-me,

thank you for these hints. Please note that I am not using cordova but capacitor for this project. And your last comment made me realize that I had to install pushy inside src-capacitor after all. I followed your capacitor docs here https://pushy.me/docs/additional-platforms/capacitor and got the plugin to install correctly, I think.

Yet, I cannot initialise Pushy following your docs. This is where it fails:

```
Modify Index File

Add the following code to your js/capacitor-welcome.js file (or any other .js custom element file), inside your connectedCallback() function so that the device will listen for push notifications:

Pushy.listen();
```

The first problem is that there is no js/capacitor-welcome.js file anywhere.
And using your suggestion (deviceready listener in a component) results in window.Pushy being an empty object. So no progress trying to initialize or even access Pushy, unfortunately.

Which also seems logical to me, because - if I install the Plugin inside the src-capacitor folder, my JS project (Vue/Quasar) can not possibly know about Pushy. 

So I wonder for what scenario your online docs for capacitor even apply.

**Comment by pushy** [comment]
@jbwl Apologies for the delayed response.

Quasar with Capacitor configured uses Cordova behind the scenes, since Capacitor is based on Ionic which is based on Cordova.

For more info on using Cordova plugins (such as this one) inside a Quasar app, please refer to the official docs, specifically **Using a Cordova Plugin**:
https://quasar.dev/quasar-cli/developing-cordova-apps/cordova-plugins#Using-a-Cordova-Plugin

Since Quasar isn't directly supported, this is all the assistance we can provide in this matter.
