### ISSUE TITLE
Possible conflicts with pushwoosh plugin?

### ISSUE THREAD

**Issue by CodeWithOz** [pushy-me/pushy-cordova#31]
We use Pushy as our primary provider of push notifications. We're considering using the [segmentation](https://blog.pushwoosh.com/blog/customer-segmentation/) features provided by pushwoosh, so I'm curious to know if there are any potential pitfalls when using both Pushy and pushwoosh and their plugins in the same app bundle (on Android or iOS). Have attempted something like this before, or are there obvious sources of conflict that would need to be resolved? Thanks in advance. :)

**Comment by CodeWithOz** [comment]
Battery performance is one thing I have in mind, but maybe there are other concerns too that you may have thought of.

**Comment by pushy** [comment]
Hi @CodeWithOz,
Nice to connect with you. Thanks for reaching out.

Since this question is not directly related to the Pushy Cordova SDK, we would like to kindly ask you to [reach out to us](https://pushy.me/contact) through our website instead, and we will be glad to provide a detailed response there.
