### ISSUE TITLE
Notifications not working for new ios devices

### ISSUE THREAD

**Issue by Omar611** [pushy-me/pushy-cordova#34]
I am using Pushy for an Ionic-Cordova app. Notifications are working for Android devices and for Old iPhones (ex iphone 7) but for iphone 12 it is not working and we can't even see the device id in the pushy dashboard and when I search for the device in the dashboard I get this message (as in the attached img).
![image](https://user-images.githubusercontent.com/45848435/149782954-d7e68512-cfd0-4b44-bac4-902773054959.png)

**Comment by pushy** [comment]
Hi @Omar611,
We'd be glad to assist.

As a reminder, you can only send notifications to Pushy device tokens returned from the "Pushy.register()" SDK method, and not directly to APNs device tokens.

Please let us know the device token you are trying to send a notification to which results in the "No devices matched the specified condition" error.

**Comment by Omar611** [comment]
This is the token for the device 43fd6f71a3dc0c20aeb2b9 
BS: the notifications works for android devices and old iPhones. So is there any tweak I should do for the new iPhones ?

**Comment by pushy** [comment]
Hi @Omar611,
We'd be glad to assist.

Pushy registered devices and their tokens are tied to a single specific Pushy dashboard app.

The device token you mentioned is registered to a Pushy app with ID `5d9226bb0d5e92160d1d0610`. Please make sure you visit the right Pushy app in your account dashboard to send a notification to this device. Here's the link, for your convenience:
https://dashboard.pushy.me/apps/5d9226bb0d5e92160d1d0610/send

When pasting this device token into the above page, it will send the notification successfully.

**Comment by Omar611** [comment]
Ok so I tried that and I got this message "We could not find an app with that ID in your account."
So does that mean that my IOS app isn't registering that phone for any reason ? 
If that is the case so why is it registering the other older iPhones ?

**Comment by pushy** [comment]
Hi @Omar611,
What that means is that your iOS device is registered to a Pushy dashboard app **in another Pushy account**, not the one you are currently logged in to in the dashboard.

When you register an iOS device for notifications with Pushy, it will automatically associate itself with the Pushy dashboard app **that bears the same iOS Bundle ID**, unless you call **Pushy.setAppId()** to override this behavior.

1) Please ensure you have an app in your Pushy dashboard account with the **same iOS Bundle ID** as your Cordova iOS Xcode project.
2) Is your app calling `Pushy.setAppId()` and passing in a Pushy app ID to override this behavior?

Most likely, the device is being associated with an app in one of your colleague's Pushy accounts, instead of your own.

**Comment by Omar611** [comment]
For no#1 I have only one dashboard that uses the same iOS Bundle ID as my Cordova iOS Xcode project.
As for no#2 should I add call this `Pushy.setAppId()` inside the callback of `Pushy.register(function (err, deviceToken) { //code}` or in the same place I call the `Pushy.setNotificationListener`

**Comment by pushy-me** [comment]
Hi @Omar611,
Thanks for clarifying

There is actually no need to call `Pushy.setAppId()` unless you have a specific reason to do so.

Please reach out to us via support@pushy.me and we'll be glad to provide more info on the account your device is getting registered to.

**Comment by pushy** [comment]
Hi @Omar611,
Thanks for clarifying.

There is actually no need to call `Pushy.setAppId()` unless you have a specific reason to do so.

Please reach out to us via support@pushy.me and we'll be glad to provide more info on the issue.
